# Generated by Django 5.2.10 on 2026-03-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
