# Generated by Django 5.2.10 on 2026-03-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
